/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance */
        post: operations["advance_api_sessions__session_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_sessions__session_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Session */
        post: operations["end_session_api_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Summary */
        get: operations["read_summary_api_sessions__session_id__summary_get"];
        put?: never;
        /** Create Summary */
        post: operations["create_summary_api_sessions__session_id__summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room */
        get: operations["get_room_api_sessions__session_id__room_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/transcript-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Transcript Draft */
        post: operations["create_transcript_draft_api_sessions__session_id__transcript_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/transcript-drafts/{draft_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Transcript Draft */
        post: operations["confirm_transcript_draft_api_sessions__session_id__transcript_drafts__draft_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/transcript-drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Discard Transcript Draft */
        delete: operations["discard_transcript_draft_api_sessions__session_id__transcript_drafts__draft_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Release */
        get: operations["release_api_release_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConversationRoomView */
        ConversationRoomView: {
            detail: components["schemas"]["SessionDetail"];
            room: components["schemas"]["RoomProjection"];
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Ladder Id */
            ladder_id: string;
            /** Restart Existing */
            restart_existing?: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageView */
        MessageView: {
            /** Seq */
            seq: number;
            /**
             * Role
             * @enum {string}
             */
            role: "student" | "tutor" | "system";
            /** Content */
            content: string;
        };
        /** ReleaseView */
        ReleaseView: {
            /** Release Id */
            release_id: string;
            /** Source Sha */
            source_sha: string;
            /** Environment */
            environment: string;
            /** Alembic Revision */
            alembic_revision: string;
            /** Built At */
            built_at: string;
        };
        /** RoomCapabilities */
        RoomCapabilities: {
            /**
             * History
             * @default true
             */
            history: boolean;
            /**
             * Text Input
             * @default true
             */
            text_input: boolean;
            /**
             * Voice Input
             * @default true
             */
            voice_input: boolean;
            /**
             * Transcript Draft
             * @default true
             */
            transcript_draft: boolean;
        };
        /** RoomProjection */
        RoomProjection: {
            /**
             * Room Revision
             * @default ce-room-v1
             */
            room_revision: string;
            /**
             * Tutor State
             * @default idle
             * @enum {string}
             */
            tutor_state: "idle" | "listening" | "thinking" | "speaking";
            /**
             * Avatar Id
             * @default brunette
             * @constant
             */
            avatar_id: "brunette";
            capabilities?: components["schemas"]["RoomCapabilities"];
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Text */
            text: string;
        };
        /** SessionDetail */
        SessionDetail: {
            session: components["schemas"]["SessionInfo"];
            stage: components["schemas"]["StageView"] | null;
            /** Messages */
            messages: components["schemas"]["MessageView"][];
            /** Available Actions */
            available_actions: ("send_message" | "advance" | "end" | "retry")[];
            summary: components["schemas"]["SummaryView"] | null;
        };
        /** SessionHistoryItem */
        SessionHistoryItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "ended";
            /**
             * Flow State
             * @enum {string}
             */
            flow_state: "active_in_stage" | "at_crossroad" | "awaiting_wrap_up" | "ended";
            /** Current Stage Index */
            current_stage_index: number;
            /** Total Stages */
            total_stages: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Ended At */
            ended_at: string | null;
            /** End Reason */
            end_reason: ("student_ended" | "completed" | "restarted") | null;
            /** Summary Preview */
            summary_preview: string | null;
            /** Stage Title */
            stage_title: string | null;
        };
        /** SessionHistoryPage */
        SessionHistoryPage: {
            /** Items */
            items: components["schemas"]["SessionHistoryItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SessionInfo */
        SessionInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "ended";
            /**
             * Flow State
             * @enum {string}
             */
            flow_state: "active_in_stage" | "at_crossroad" | "awaiting_wrap_up" | "ended";
            /** Current Stage Index */
            current_stage_index: number;
            /** Total Stages */
            total_stages: number;
            /** End Reason */
            end_reason?: ("student_ended" | "completed" | "restarted") | null;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** SessionView */
        SessionView: {
            session: components["schemas"]["SessionInfo"];
            stage: components["schemas"]["StageView"] | null;
            /** Appended Messages */
            appended_messages: components["schemas"]["MessageView"][];
            /** Available Actions */
            available_actions: ("send_message" | "advance" | "end" | "retry")[];
            summary: components["schemas"]["SummaryView"] | null;
        };
        /** StageOutcomeView */
        StageOutcomeView: {
            /** Index */
            index: number;
            /**
             * Status
             * @enum {string}
             */
            status: "not_started" | "in_progress" | "goal_met" | "capped" | "stopped_early" | "skipped";
            /** Title */
            title: string | null;
        };
        /**
         * StageView
         * @description 只描述學生已經進入的情境。
         */
        StageView: {
            /** Index */
            index: number;
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Opening Statement */
            opening_statement: string;
        };
        /** SummaryView */
        SummaryView: {
            /**
             * Discussion Topic
             * @default 電車難題：選擇、責任與原則
             */
            discussion_topic: string;
            /** Core Principle */
            core_principle: string;
            /** Key Points */
            key_points?: string[];
            /**
             * Tension
             * @default
             */
            tension: string;
            /** Reflection Excerpt */
            reflection_excerpt?: string | null;
            /** Stage Outcomes */
            stage_outcomes: components["schemas"]["StageOutcomeView"][];
        };
        /** TranscriptDraftCreate */
        TranscriptDraftCreate: {
            /** Text */
            text: string;
            /**
             * Adapter
             * @default browser-speech
             */
            adapter: string;
            /**
             * Locale
             * @default zh-TW
             */
            locale: string;
            /** Confidence */
            confidence?: number | null;
        };
        /** TranscriptDraftView */
        TranscriptDraftView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Text */
            text: string;
            /** Adapter */
            adapter: string;
            /** Locale */
            locale: string;
            /** Confidence */
            confidence: number | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Discarded At */
            discarded_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header: {
                "x-learner-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionHistoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_api_sessions__session_id__advance_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_sessions__session_id__retry_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_summary_api_sessions__session_id__summary_get: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_summary_api_sessions__session_id__summary_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_room_api_sessions__session_id__room_get: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRoomView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transcript_draft_api_sessions__session_id__transcript_drafts_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscriptDraftCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptDraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_transcript_draft_api_sessions__session_id__transcript_drafts__draft_id__confirm_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptDraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_transcript_draft_api_sessions__session_id__transcript_drafts__draft_id__delete: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptDraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    release_api_release_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseView"];
                };
            };
        };
    };
}
