/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_sessions__session_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Session */
        post: operations["end_session_api_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Summary */
        get: operations["read_summary_api_sessions__session_id__summary_get"];
        put?: never;
        /** Create Summary */
        post: operations["create_summary_api_sessions__session_id__summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Ladder Id */
            ladder_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageView */
        MessageView: {
            /** Seq */
            seq: number;
            /**
             * Role
             * @enum {string}
             */
            role: "student" | "tutor" | "system";
            /** Content */
            content: string;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Text */
            text: string;
        };
        /**
         * SessionDetail
         * @description GET 專用：回傳完整訊息而非增量。
         */
        SessionDetail: {
            session: components["schemas"]["SessionInfo"];
            stage: components["schemas"]["StageView"] | null;
            /** Messages */
            messages: components["schemas"]["MessageView"][];
            /** Available Actions */
            available_actions: ("send_message" | "advance" | "end" | "retry")[];
            summary: components["schemas"]["SummaryView"] | null;
        };
        /** SessionInfo */
        SessionInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "ended";
            /**
             * Flow State
             * @enum {string}
             */
            flow_state: "active_in_stage" | "at_crossroad" | "awaiting_wrap_up" | "ended";
            /** Current Stage Index */
            current_stage_index: number;
            /** Total Stages */
            total_stages: number;
            /** End Reason */
            end_reason?: ("student_ended" | "completed" | "restarted") | null;
        };
        /**
         * SessionView
         * @description 所有會改變狀態的端點共用的回應形狀（設計規格 §9.1）。
         */
        SessionView: {
            session: components["schemas"]["SessionInfo"];
            stage: components["schemas"]["StageView"] | null;
            /** Appended Messages */
            appended_messages: components["schemas"]["MessageView"][];
            /** Available Actions */
            available_actions: ("send_message" | "advance" | "end" | "retry")[];
            summary: components["schemas"]["SummaryView"] | null;
        };
        /** StageOutcomeView */
        StageOutcomeView: {
            /** Index */
            index: number;
            /**
             * Status
             * @enum {string}
             */
            status: "not_started" | "in_progress" | "goal_met" | "capped" | "stopped_early" | "skipped";
            /** Title */
            title: string | null;
        };
        /**
         * StageView
         * @description 只描述學生**已經進入**的那一階。未進入的階不會出現在任何回應裡。
         */
        StageView: {
            /** Index */
            index: number;
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Opening Statement */
            opening_statement: string;
        };
        /** SummaryView */
        SummaryView: {
            /** Core Principle */
            core_principle: string;
            /** Stage Outcomes */
            stage_outcomes: components["schemas"]["StageOutcomeView"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_sessions__session_id__retry_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_summary_api_sessions__session_id__summary_get: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_summary_api_sessions__session_id__summary_post: {
        parameters: {
            query?: never;
            header: {
                "x-learner-id": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
