"""Classroom (Run 2) schema, squashed from 0006–0104 on 2026-10-05.

Generated by `alembic revision --autogenerate` against a database at 9a0c1d2e3f42, so it
is what the ORM declared that day — and it imports nothing from app, so it stays that way
after the ORM moves on. The six revisions it replaces only ever ran on stage and on
developers' machines. A database left on any of them must be dropped and recreated before
this migration is deployed; alembic refuses it with "Can't locate revision" rather than
migrating it.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: Union[str, None] = "9a0c1d2e3f42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "library_receipts",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "llm_budget",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("calls", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mail_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("next_at", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt_programs",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_buckets",
        sa.Column("id", sa.String(length=150), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rate_buckets_expires_at"), "rate_buckets", ["expires_at"], unique=False
    )
    op.create_table(
        "classroom_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("assets", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classroom_assets_owner_id"), "classroom_assets", ["owner_id"], unique=False
    )
    op.create_table(
        "email_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_email_tokens_account_id"), "email_tokens", ["account_id"], unique=False
    )
    op.create_table(
        "login_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_login_sessions_account_id"), "login_sessions", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_login_sessions_expires_at"), "login_sessions", ["expires_at"], unique=False
    )
    op.create_table(
        "mail_delivery",
        sa.Column("mail_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("html_body", sa.Text(), nullable=True),
        sa.Column("preview_url", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("provider_message_id", sa.String(length=160), nullable=True),
        sa.Column("provider_status", sa.String(length=40), nullable=False),
        sa.Column("lease", sa.String(length=36), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("events", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("sent_at", sa.Float(), nullable=True),
        sa.Column("delivered_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mail_id"],
            ["mail_outbox.id"],
        ),
        sa.PrimaryKeyConstraint("mail_id"),
    )
    op.create_index(
        op.f("ix_mail_delivery_account_id"), "mail_delivery", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_mail_delivery_created_at"), "mail_delivery", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_mail_delivery_idempotency_key"), "mail_delivery", ["idempotency_key"], unique=True
    )
    op.create_index(
        op.f("ix_mail_delivery_provider_message_id"),
        "mail_delivery",
        ["provider_message_id"],
        unique=False,
    )
    op.create_index(op.f("ix_mail_delivery_purpose"), "mail_delivery", ["purpose"], unique=False)
    op.create_table(
        "provider_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("adapter", sa.String(length=32), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("organization", sa.String(length=200), nullable=True),
        sa.Column("project", sa.String(length=200), nullable=True),
        sa.Column("default_model", sa.String(length=200), nullable=False),
        sa.Column("credential_mode", sa.String(length=24), nullable=False),
        sa.Column("encrypted_secret", sa.Text(), nullable=True),
        sa.Column("secret_last4", sa.String(length=4), nullable=True),
        sa.Column("key_version", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name"),
    )
    op.create_index(
        op.f("ix_provider_profiles_owner_id"), "provider_profiles", ["owner_id"], unique=False
    )
    op.create_table(
        "scripts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scripts_owner_id"), "scripts", ["owner_id"], unique=False)
    op.create_table(
        "account_ai_settings",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("default_profile_id", sa.String(length=36), nullable=True),
        sa.Column("fallback_profile_id", sa.String(length=36), nullable=True),
        sa.Column("model_matrix", sa.JSON(), nullable=False),
        sa.Column("budgets", sa.JSON(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_profile_id"],
            ["provider_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fallback_profile_id"],
            ["provider_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "script_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("script_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["script_id"],
            ["scripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_script_snapshots_script_id"), "script_snapshots", ["script_id"], unique=False
    )
    op.create_table(
        "session_provider_secrets",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=False),
        sa.Column("encrypted_secret", sa.Text(), nullable=False),
        sa.Column("secret_last4", sa.String(length=4), nullable=False),
        sa.Column("key_version", sa.String(length=40), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["provider_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_token_hash"],
            ["login_sessions.token_hash"],
        ),
        sa.PrimaryKeyConstraint("profile_id", "session_token_hash"),
    )
    op.create_index(
        op.f("ix_session_provider_secrets_expires_at"),
        "session_provider_secrets",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "classroom_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("creator_id", sa.String(length=36), nullable=False),
        sa.Column("script_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.Float(), nullable=True),
        sa.Column("llm_used", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["script_id"],
            ["scripts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["script_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_classroom_runs_creator_id"), "classroom_runs", ["creator_id"], unique=False
    )
    op.create_index(op.f("ix_classroom_runs_due_at"), "classroom_runs", ["due_at"], unique=False)
    op.create_table(
        "action_receipts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("action_id", sa.String(length=100), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("receipt", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["classroom_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "actor_id", "action_id"),
    )
    op.create_index(
        op.f("ix_action_receipts_room_id"), "action_receipts", ["room_id"], unique=False
    )
    op.create_table(
        "ai_students",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("parent_room_id", sa.String(length=36), nullable=False),
        sa.Column("persona", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("provider_profile_id", sa.String(length=36), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_room_id"],
            ["classroom_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_profile_id"],
            ["provider_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_index(
        op.f("ix_ai_students_parent_room_id"), "ai_students", ["parent_room_id"], unique=False
    )
    op.create_table(
        "classroom_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["classroom_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "seq"),
    )
    op.create_index(
        op.f("ix_classroom_events_room_id"), "classroom_events", ["room_id"], unique=False
    )
    op.create_table(
        "classroom_sessions",
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("classroom_id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classroom_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["classroom_runs.id"],
        ),
        sa.PrimaryKeyConstraint("room_id"),
    )
    op.create_index(
        op.f("ix_classroom_sessions_batch_id"), "classroom_sessions", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_classroom_sessions_classroom_id"),
        "classroom_sessions",
        ["classroom_id"],
        unique=False,
    )
    op.create_table(
        "llm_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("logical_key", sa.String(length=150), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("next_at", sa.Float(), nullable=False),
        sa.Column("lease", sa.String(length=36), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("audit", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["classroom_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "logical_key"),
    )
    op.create_index(op.f("ix_llm_jobs_next_at"), "llm_jobs", ["next_at"], unique=False)
    op.create_index(op.f("ix_llm_jobs_room_id"), "llm_jobs", ["room_id"], unique=False)
    op.create_index(op.f("ix_llm_jobs_state"), "llm_jobs", ["state"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=False),
        sa.Column("avatar", sa.String(length=64), nullable=False),
        sa.Column("seat", sa.Integer(), nullable=True),
        sa.Column("last_seen", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["classroom_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "account_id", "role"),
        sa.UniqueConstraint("room_id", "seat"),
    )
    op.create_index(op.f("ix_memberships_account_id"), "memberships", ["account_id"], unique=False)
    op.create_index(op.f("ix_memberships_room_id"), "memberships", ["room_id"], unique=False)
    op.create_table(
        "question_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("question_index", sa.Integer(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["classroom_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_question_runs_room_id"), "question_runs", ["room_id"], unique=False)
    op.create_table(
        "llm_call_audit",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["llm_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_call_audit_job_id"), "llm_call_audit", ["job_id"], unique=False)
    op.create_table(
        "point_ledger",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("action_id", sa.String(length=100), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("focus_id", sa.String(length=36), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=12), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["memberships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["classroom_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "action_id", "account_id", "side"),
    )
    op.create_index(
        op.f("ix_point_ledger_account_id"), "point_ledger", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_point_ledger_room_id"), "point_ledger", ["room_id"], unique=False)
    op.create_table(
        "question_answers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("question_run_id", sa.String(length=36), nullable=False),
        sa.Column("membership_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_run_id"],
            ["question_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["classroom_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_run_id", "membership_id"),
    )
    op.create_index(
        op.f("ix_question_answers_room_id"), "question_answers", ["room_id"], unique=False
    )


def downgrade() -> None:
    raise RuntimeError("The classroom schema is forward-only. Restore from a backup instead.")
